id: PE6238A2B
initial_creation_type: input
source_metadata:
  title: Ten Royal Sūtras
  language: pt
  description: 'A collection related to the ten royal sūtras or ten sūtras of the
    king (rgyal po''i mdo bcu), which are said to have been translated upon the advice
    of Padmasambhava for Emperor Tri Songdetsen''s daily recitation:'
  volume:
    e22a896fef134e6ea7cf85a13ec2c458:
      title: Outline of the Ten Royal Sūtras
      parent: Outlines
    59b7df138765425cb1590d9dac148ff4:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtras
    8f6da0b090c546d7a881593b42c326ae:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Sūtras
    9301c51261d0434295c680fd02a17eab:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtras
    79da4d3ae71e40af83094e62772c667d:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtras
    eb1b51f716544111bca5e52bc9cfd0bc:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Sūtras
    6c7ebbd3c67f4620ba4b9757621760a6:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Sūtras
    61a3a134c1484ee1b6c3750fe5f5df89:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtras
    a77f491615334ea2ad16df7b2079f57a:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtras
    426c41a8f3554f10a3ac5ffca093d2bb:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtras
    7527fc89f16542f9aface898b09aa46c:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Sūtras
created_at: '2022-03-01T06:06:38.014834'
last_modified_at: '2022-03-01T06:06:38.014836'
